"""add_priority_to_connectors

Revision ID: e88bf79f0197
Revises: 250c8bc43fea
Create Date: 2026-05-05 16:13:57.934700
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88bf79f0197'
down_revision: Union[str, None] = '250c8bc43fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('priority', sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connectors', 'priority')
    # ### end Alembic commands ###
